### ISSUE TITLE
No image folder checked into repo

### ISSUE THREAD

**Issue by nisrulz** [openwichita/lake-afton-interactive-exhibits#22]
The presentations , all of them refer to images in slides from `src/img` folder which doesnot exist in the repo. So either the `img` folder was not checked in and should get fixed by checking that in or the links need to be via the internet.

To verify this, load up any slide and check the chrome console for errors.

**Comment by DJSethDuncan** [comment]
In the readme file it actually talks about how to download those files via dropbox. I could see an argument for actually including the empty folder in the repo, though.

**Comment by infernocloud** [comment]
Git is actually weird about committing empty folders - it really only cares about files. You can hack git into committing an empty folder if you make it not so empty, by including a .gitignore in the folder or some other empty file (.keep, etc).

Since the readme does describe how to get the images and where to place them I'm going to close this issue. We could possibly reorganize the readme to make it more clear that creating this folder and adding the images are necessary. Maybe eventually an init script could automate this.
