### ISSUE TITLE
Create a presentation about black holes

### ISSUE THREAD

**Issue by infernocloud** [openwichita/lake-afton-interactive-exhibits#9]

**Comment by VickySteeves** [comment]
I'd love to take this one!

**Comment by VickySteeves** [comment]
Hi! I'm ready to make my pull request but had two questions:

1. Are you going to grab the images I've used in my presentation for your dropbox folder, or link out forever? Because I don't want to keep them forever in mine :wink: 

2. Is there a reason you don't just include the reveal.js files in your repo? They don't take up that much space, and actually, `black.css` isn't included when you `npm install reveal` locally. I had to seek it out from the original reveal repo.

**Comment by DJSethDuncan** [comment]
Hey Vicky,

We were doing the npm method at first but I think we're going to transition to just using reveal.js since it's created something of a barrier for entry for some people who want to contribute but aren't seasoned devs.

I'll grab the photos from your presentation and get them in the dropbox. Thanks!
